### ISSUE TITLE
Question: Multiple Rows?

### ISSUE THREAD

**Issue by rpattabi** [nex3z/ToggleButtonGroup#12]
Is it possible to arrange a group of toggle buttons in multiple rows and columns, sort of like

![image](https://user-images.githubusercontent.com/174775/29861085-afdfc018-8d85-11e7-98d8-f324c7909eca.png)

**Comment by nex3z** [comment]
By setting `app:tbgFlow="true"`, buttons are moved to next row when there is no enough space in current row, as shown [here](https://github.com/nex3z/ToggleButtonGroup#flow-buttons-to-next-row).

If all buttons are of the same size, they will be nicely aligned. Unfortunately you can't specify the number of rows or columns directly. But you can set the width of the `ToggleButtonGroup` to be the number of columns multiplies the width of the button, so that buttons are moved to next row when they hit the specified column number. 

For example, each button below has a width of 40dp, by setting `android:layout_width="280dp"` and `app:tbgFlow="true"`, there is 7 buttons in each row :

![device-2017-08-30-161548](https://user-images.githubusercontent.com/5645004/29862256-aa0ad402-8d9e-11e7-81d9-d0f35e2ec9dd.png)

**Comment by rpattabi** [comment]
Awesome. I see flow layout is supported out of the box. Similarly, would it be possible to add a feature that allows constraint layout for the arrangement of the buttons? That would make button group versatile.

**Comment by nex3z** [comment]
The original goal of ToggleButtonGroup and Flowlayout were to layout views with different sizes. Because we don't know the size of each view beforehand, we need ToggleButtonGroup/Flowlayout to measure and layout each view properly. 

Features for pre-defining the layout (eg. Guidelines in ConstraintLayout) would break the "flowable" behavior of the current lib, which I think needs further consideration and will not be added in short terms.

For the button grid scenario, I would also give a try at [GridLayout](https://developer.android.com/reference/android/widget/GridLayout.html), which is more specialized on grid like layout and saves a lot guideline boilerplates as in ConstraintLayout. In this case, [indexOfChild()](https://developer.android.com/reference/android/view/ViewGroup.html#indexOfChild(android.view.View)) and [getChildAt()](https://developer.android.com/reference/android/view/ViewGroup.html#getChildAt(int)) is handy to keep records of the checked positions if the buttons are checkable.

Thanks for your advice.
