### ISSUE TITLE
get position of selected 

### ISSUE THREAD

**Issue by IgordeOliveira** [nex3z/ToggleButtonGroup#20]
I have a MultiSelectToggleGroup with all the days of the week as in the image, I need to check these days (if they beat the current day), but not to use the texts because it has repeated (SATURDAY and SUNDAY is "S"), how do I get the position of items checked? or another way to do it?

![image](https://user-images.githubusercontent.com/19624377/34234521-bfebab52-e5d2-11e7-89e8-4a54bcb3b2ad.png)

**Comment by nex3z** [comment]
You can use [`T findViewById (int id)`](https://developer.android.com/reference/android/view/View.html#findViewById(int)) and [`int indexOfChild (View child)`](https://developer.android.com/reference/android/view/ViewGroup.html#indexOfChild(android.view.View)) to find the position of a button:

```java
final MultiSelectToggleGroup multi = (MultiSelectToggleGroup) findViewById(R.id.group_weekdays);

Set<Integer> checkedIds = multi.getCheckedIds();
Set<Integer> positions = new HashSet<>(); // Holder for all checked positions
for (int id : checkedIds) {
    View view = multi.findViewById(id);
    int position = multi.indexOfChild(view);
    positions.add(position);
}
```
You can also add extra data like position on each button using [tags](https://developer.android.com/reference/android/view/View.html#Tags), so that you can get the position from the button directly.

**Comment by IgordeOliveira** [comment]
Works, thanks
