### ISSUE TITLE
old attributes

### ISSUE THREAD

**Issue by alfaaluska** [nex3z/ToggleButtonGroup#21]
How can I set these attributes programmatically? because I'm still using the old version and trying to update the button.

```
app:tbgButtonTextPaddingLeft="16dp"
app:tbgButtonTextPaddingRight="16dp"
```

Because when I try to use ` toggle.setBackground(getResources().getDrawable(R.drawable.round_rect_button_bg));
toggle.setPadding(16,0,16,0);`

Then it becomes like this:
![screenshot_20180128-124148 1](https://user-images.githubusercontent.com/21968935/35479387-c38f30d4-0428-11e8-82e9-eb32fd396c83.png)

My layout
```
            <com.nex3z.togglebuttongroup.SingleSelectToggleGroup
                app:paddingEnd="20dp"
                app:paddingStart="20dp"
                app:tbgChildSpacingForLastRow="align"
                app:tbgChildSpacing="auto"
                app:tbgFlow="true"
                app:tbgRowSpacing="8dp"
                app:tbgCheckedButton="@drawable/round_rect_checked_bg"
                android:paddingTop="10dp"
                android:layout_centerInParent="true"
                android:id="@+id/nominal"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:padding="20dp"
                android:textColor="@color/selector_text"
                android:textSize="16sp" />
```

Thanks before!

**Comment by nex3z** [comment]
If you are using v0.2.3 or before,  call [`setTextPadding()`](https://github.com/nex3z/ToggleButtonGroup/blob/f7806e622294a5d615f0b33f630f6d8710ed0a28/togglebuttongroup/src/main/java/com/nex3z/togglebuttongroup/ToggleButton.java#L148) on [`ToggleButton`](https://github.com/nex3z/ToggleButtonGroup/blob/f7806e622294a5d615f0b33f630f6d8710ed0a28/togglebuttongroup/src/main/java/com/nex3z/togglebuttongroup/ToggleButton.java) to set paddings for button text.

For example, with the following code:

```java
final MultiSelectToggleGroup multi =
        (MultiSelectToggleGroup) findViewById(R.id.multi_dummy_text);

for (int i = 0; i < multi.getChildCount(); i++) {
    View child = multi.getChildAt(i);
    if (child instanceof ToggleButton) {
         // Set text padding in px on left and right
        ((ToggleButton) child).setTextPadding(dpToPx(8), 0, dpToPx(8), 0);
    }
}
```
```java
private int dpToPx(float dp){
    return (int) TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, dp,
            getResources().getDisplayMetrics());
}
```

and the layout:

```xml
<com.nex3z.togglebuttongroup.MultiSelectToggleGroup
    android:id="@+id/multi_dummy_text"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_marginTop="32dp"
    android:textSize="16sp"
    android:textColor="@color/selector_text"
    app:tbgButtonHeight="40dp"
    app:tbgButtonWidth="wrap_content"
    app:tbgTextButtons="@array/dummy_text"
    app:tbgCheckedBackground="@drawable/round_rect_checked_bg"
    app:tbgButtonBackground="@drawable/round_rect_button_bg"
    app:tbgFlow="true"
    app:tbgButtonSpacing="auto"
    app:tbgRowSpacing="8dp"
    app:tbgAnimationType="alpha" />
```

will produce:

![screen shot 2018-01-28 at 4 42 17 pm](https://user-images.githubusercontent.com/5645004/35480494-3e4a3f3c-044a-11e8-90d1-e175cbe08e68.png)

Notice that if you want the size of the button to change corresponding to the padding, you will need to set `app:tbgButtonWidth="wrap_content"`, so that the button can resize itself automatically.
