### ISSUE TITLE
Set ToggleButton to Checked state by the string text?

### ISSUE THREAD

**Issue by usmaan-anwar** [nex3z/ToggleButtonGroup#41]
Actually I am using your library to let the user select their "Interests", I am programmatically creating the interests and save the selected one on server as strings, then when a user logs in I get his interests as strings, I just want to know how can I set checked on those buttons which user has selected using the string values?
Thanks a lot for your help!

**Comment by nex3z** [comment]
For a straight forward solution, you can iterate through all the selected interests and all the buttons, check the button if its text matches the selected interest.

```java
String[] selectedInterests = {"Hiking", "Skiing"}; // These are the seleced interests you get from server
for (int i = 0; i < interestsMultiSelectToggleGroup.getChildCount(); i++) { // Iterate through all the button in the toggle group
    LabelToggle toggle = (LabelToggle) interestsMultiSelectToggleGroup.getChildAt(i);
    for (String selected : selectedInterests) { // Iterate through all the selected interests to find a match
        if (toggle.getText().equals(selected)) {
            toggle.setChecked(true);
        }
    }
}
```
![device-2018-10-06-222238](https://user-images.githubusercontent.com/5645004/46572320-60333680-c9b6-11e8-90f6-b6c79e9f49d9.png)

This works if the total number of interests is small, that iterate through all the interests is cheap.

If you have many interests, you'd better use some kind of `Map` to map interest string to the corresponding button (or its position in the toggle group), so that you can get the button by interest text much more efficiently.

**Comment by usmaan-anwar** [comment]
Thanks a lot Man, believe me **You** are the **Best**.
